import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { connectToDatabase } from "@/services/mongo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App (App Dir + Tailwind CSS)",
  description: "Generated by create next app",
};

const poppins = Inter({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "700"]
});
export default async function RootLayout({ children }) {
  const conn = await connectToDatabase();
  console.log("Database connection status:", conn);
  return (
    <html lang="en">
      <body
        className={cn(`${geistSans.variable} ${geistMono.variable} antialiased`, poppins.className)}
      >
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
